site_name: ECA - Editor Code Assistant
site_description: ECA - AI pair programming capabilities in any editor
site_url: https://eca.dev

repo_name: editor-code-assistant/eca
repo_url: https://github.com/editor-code-assistant/eca

nav:
  - Home:
    - Overview: README.md
    - Configuration: configuration.md
    - Models: models.md
    - Development: development.md
    - Protocol: protocol.md
  - Features: features.md
  - Installation: installation.md
  - Models: models.md
  - Support Us: https://github.com/sponsors/ericdallo
  - Changelog: CHANGELOG.md

theme:
  name: material
  logo: images/logo.svg
  favicon: images/logo.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/editor-code-assistant/eca

extra_css:
  - stylesheets/layout.css

markdown_extensions:
  - pymdownx.superfences
  - codehilite
  - meta
  - toc:
      permalink: '#'
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized

google_analytics:
  - G-VFJYDKR1MR
  - auto
