site_name: ECA - Editor Code Assistant
site_description: ECA - AI pair programming capabilities in any editor
site_url: https://eca.dev

repo_name: editor-code-assistant/eca
repo_url: https://github.com/editor-code-assistant/eca

nav:
  - Home:
    - Overview: README.md
    - Configuration: configuration.md
    - Development: development.md
    - Models: models.md
    - Protocol: protocol.md
  - Features: features.md
  - Installation: installation.md
  - Support Us: https://github.com/sponsors/ericdallo
  - Changelog: CHANGELOG.md

theme:
  name: material
  logo: images/logo.png
  favicon: images/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/editor-code-assistant/eca

extra_css:
  - stylesheets/layout.css

markdown_extensions:
  - pymdownx.superfences
  - codehilite
  - meta
  - toc:
      permalink: '#'
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized
