name: Docs

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'resources/ECA_VERSION'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate docs
        run: |
          cp -rf CHANGELOG.md README.md images docs
          docker login docker.pkg.github.com --username $GITHUB_ACTOR --password ${{ secrets.GITHUB_TOKEN }}
          docker run --rm -v ${PWD}:/docs ghcr.io/editor-code-assistant/docs-image/docs-image -- build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
